# === GENERAL ===
model: DLiteExample
reset: true
cfg: null
out_path: /home/ryuuyou/E5/project/DLite/out
# out_path: /share/home/liuy/project/DLite/out

# === RAY DISTRIBUTED ===
ray_address: null
num_workers: 1
gpus_per_worker: 1.0
cpus_per_worker: 2

# === Trainer ===
trainer: BaseTrainer
epochs: 10
save_every: 1

# === Architecture ===
arch: ExampleMLP
input_dim: 1024
output_dim: 32

# === Dataset ===
train_data_path: data
val_data_path: null
train_dataset: ExampleRandomDataset
val_dataset: null
batch_size_per_worker: 8
shuffle: true
workers: 2

# === Loss ===
loss: ExampleLoss

# === Optimizer & Scheduler ===
optimizer: adam
scheduler: warmup
# lr_start: 0.0005
# lr_end: 0.000001
# lr_warmup: 10
